name: Deployment
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configure Env Variables
        if: github.ref == 'refs/heads/master'
        run: |
          echo "STAGE=dev" >> $GITHUB_ENV
          echo "UI_S3_BUCKET=minerva-avalie-ui-dev" >> $GITHUB_ENV
          echo "DISTRIBUTION_ID=I33GCYMLM1FZ3B" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Node dependencies
        run: npm install && npm install -g @aws-amplify/cli
      - name: Build frontend
        run: npm run build:$STAGE
      - name: Move static files to s3
        run: aws s3 sync ./dist s3://$UI_S3_BUCKET
      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
